package uniandes.edu.co.proyecto.modelo;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;

@Entity
@Table(name = "habitaciones")
public class HabitacionEntity {
    // primary key autogenerated
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "habitaciones_sequence")
    @SequenceGenerator(name = "habitaciones_sequence", sequenceName = "habitaciones_sequence", allocationSize = 1)
    private Integer id_habitacion;

    // attributes
    private Integer consumo_acumulado;
    private Character disponibilidad;

    @ManyToOne
    @JoinColumn(name = "tipos_habitacion_id_tipo", referencedColumnName = "id_tipo")
    private TipoHabitacionEntity tipos_habitacion_id_tipo;

    // constructor
    public HabitacionEntity(Integer consumo_acumulado, Character disponibilidad, TipoHabitacionEntity tipos_habitacion_id_tipo) {
        this.consumo_acumulado = consumo_acumulado;
        this.disponibilidad = disponibilidad;
        this.tipos_habitacion_id_tipo = tipos_habitacion_id_tipo;
    }

    // constructor vacío
    public HabitacionEntity() {
        ;
    }

    // getters & setters
    public Integer getId_habitacion() {
        return id_habitacion;
    }

    public void setId_habitacion(Integer id_habitacion) {
        this.id_habitacion = id_habitacion;
    }

    public Integer getConsumo_acumulado() {
        return consumo_acumulado;
    }

    public void setConsumo_acumulado(Integer consumo_acumulado) {
        this.consumo_acumulado = consumo_acumulado;
    }

    public Character getDisponibilidad() {
        return disponibilidad;
    }

    public void setDisponibilidad(Character disponibilidad) {
        this.disponibilidad = disponibilidad;
    }

    public TipoHabitacionEntity getTipos_habitacion_id_tipo() {
        return tipos_habitacion_id_tipo;
    }

    public void setTipos_habitacion_id_tipo(TipoHabitacionEntity tipos_habitacion_id_tipo) {
        this.tipos_habitacion_id_tipo = tipos_habitacion_id_tipo;
    }

    public class RespuestaReq1 {
    }

}
