package uniandes.edu.co.proyecto.modelo;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;

@Entity
@Table(name = "Servicios")
public class ServicioEntity {
    // primary key autogenerated
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "servicios_sequence")
    @SequenceGenerator(name = "servicios_sequence", sequenceName = "servicios_sequence", allocationSize = 1)
    private Integer id_servicio;

    // attributes
    private Character disponibilidad;
    private String nombre;
    private String descripcion;

    @ManyToOne
    @JoinColumn(name = "tipos_servicio_id_tipo_ser", referencedColumnName = "tipo_servicio")
    private TipoServicioEntity tipos_servicio_id_tipo_ser;

    // constructor
    public ServicioEntity(Character disponibilidad, String nombre,
            String descripcion, TipoServicioEntity tipos_servicio_id_tipo_ser) {
        this.disponibilidad = disponibilidad;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.tipos_servicio_id_tipo_ser = tipos_servicio_id_tipo_ser;
    }

    // empty constructor
    public ServicioEntity() {
        ;
    }

    // getters & setters
    public Integer getId_servicio() {
        return id_servicio;
    }

    public void setId_servicio(Integer id_servicio) {
        this.id_servicio = id_servicio;
    }

    public Character getDisponibilidad() {
        return disponibilidad;
    }

    public void setDisponibilidad(Character disponibilidad) {
        this.disponibilidad = disponibilidad;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public TipoServicioEntity getTipos_servicio_id_tipo_ser() {
        return tipos_servicio_id_tipo_ser;
    }

    public void setTipos_servicio_id_tipo_ser(TipoServicioEntity tipos_servicio_id_tipo_ser) {
        this.tipos_servicio_id_tipo_ser = tipos_servicio_id_tipo_ser;
    }

}
